-- MySQL Script generated by MySQL Workbench
-- Tue Sep 19 20:07:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema DB_BEERCRAFT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_BEERCRAFT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_BEERCRAFT` ;
USE `DB_BEERCRAFT` ;

-- -----------------------------------------------------
-- Table `DB_BEERCRAFT`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_BEERCRAFT`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `id_rol_UNIQUE` (`id_rol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_BEERCRAFT`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_BEERCRAFT`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `admin` BIT(1) NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `user_has_rol_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `user_has_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `DB_BEERCRAFT`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_BEERCRAFT`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_BEERCRAFT`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_product` BIGINT NOT NULL,
  `id_user` INT NOT NULL,
  `amount` DECIMAL(6,2) NOT NULL,
  `purchase_date` TIMESTAMP NULL,
  PRIMARY KEY (`id_order`),
  UNIQUE INDEX `id_order_UNIQUE` (`id_order` ASC) VISIBLE,
  INDEX `order_has_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `order_has_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `DB_BEERCRAFT`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_BEERCRAFT`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_BEERCRAFT`.`products` (
  `id_product` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(150) NULL,
  `img_url` VARCHAR(350) NULL,
  `abv` DOUBLE NOT NULL,
  `origin` VARCHAR(100) NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  `size` INT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id_product`),
  UNIQUE INDEX `id_product_UNIQUE` (`id_product` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_BEERCRAFT`.`products_has_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_BEERCRAFT`.`products_has_orders` (
  `products_id_product` BIGINT NOT NULL,
  `orders_id_order` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`products_id_product`, `orders_id_order`),
  INDEX `fk_products_has_orders_orders1_idx` (`orders_id_order` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_orders_products`
    FOREIGN KEY (`products_id_product`)
    REFERENCES `DB_BEERCRAFT`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_orders_orders1`
    FOREIGN KEY (`orders_id_order`)
    REFERENCES `DB_BEERCRAFT`.`orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
